version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '35432:5432'
    volumes:
      - db-hv:/var/lib/postgresql/data

  dbsetup:
    image: postgres:14.1-alpine
    depends_on:
      - db
    restart: "no"
    entrypoint: [ "bash", "-c", "echo 'create database hvdb' | PGPASSWORD=postgres psql -h db --port 5432 -U postgres postgres "]

  mqttbroker:
    image: hivemq/hivemq-ce:2021.3
    platform: linux/amd64
    ports:
      - '56321:1883'

  hvtask:
    build: .
    depends_on:
      - dbsetup
      - mqttbroker
    environment:
      - DBHOST=db
      - DBPORT=5432
    image: hvtask:latest
    ports:
      - '38080:8080'

volumes:
  db-hv:
    driver: local
